### ISSUE TITLE
Setup Instructions?

### ISSUE THREAD

**Issue by harrywang** [vormwald/joon#10]
Hi, Thanks a lot for this great theme - I am new to Jekyll and want to know whether you can provide any instructions on how to set this up. I have forked your repo but my site does not work well: https://github.com/harrywang/harrywang.github.io. Thanks!

**Comment by harrywang** [comment]
I get the blog working locally at http://127.0.0.1:4000/blog/ by doing the following:

```
gem install jekyll
gem install bundler
bundle install
bundle exec jekyll serve
```

Then, how to make the site work on github pages? Sorry if this is a naive question.

**Comment by javiergamarra** [comment]
It's working fine here: http://harrywang.github.io/ but you are using blog/ as the main site and your static resources are in / folder. Use / as your root or move the static files.

**Comment by harrywang** [comment]
@nhpatt thanks a lot!! Now it's working :).
